### ISSUE TITLE
I want to set base_directory or prefix for uploaded file or image

### ISSUE THREAD

**Issue by hai-ru** [UniSharp/laravel-filemanager#603] opened 2018-05-22 00:10 UTC
I want to have prefix uploaded file to "/site/" because my framework in site folder. because my public in "../public_html/", the problem is if i set base_directory it make folder in framework but not in public.
![image](https://user-images.githubusercontent.com/24634668/40335609-c765f372-5d8e-11e8-9b5a-a64fd10f03f8.png)

**Comment by hai-ru** [comment] 2018-05-22 00:16
I can fix it with set base_direcctory = '../site/public' . thank you

**Comment by AnimalInstinct** [comment] 2018-07-04 16:09
I have same problem, ../../ doesnt works

**Comment by g0110280** [comment] 2018-12-05 17:49
Duplicate of #506 .

**Closed by g0110280** 2018-12-05 17:49 UTC
