### ISSUE TITLE
Should display a valid error message when max upload size exceeds

### ISSUE THREAD

**Issue by mayeenulislam** [UniSharp/laravel-filemanager#607] opened 2018-05-27 07:50 UTC
* Operating system : Windows XP, Windows 10
 * Laravel version : 5.6.16
 * Package version : ~1.8
 * Steps to reproduce your issue :
   * Check the `max_file_size` in `config/lfm.php`
   * Try to upload a file exceeding the declaration
   * You will get the following error:
> Warning: POST Content-Length of 16687728 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
> { "message": "" }

 * Screenshots of browser console :
![laravel-filemanager-max-upload-size-exceeds](https://user-images.githubusercontent.com/4551598/40583641-952fae28-61b4-11e8-8170-ec01d5e8023e.png)

## EXPECTED BEHAVIOR
A nice error message like below:
> The file exceeds the maximum upload size, and **cannot be uploaded**

**Comment by g0110280** [comment] 2018-12-05 18:00
Duplicate of #608 .

**Closed by g0110280** 2018-12-05 18:00 UTC
Labels: enhancement
