### ISSUE TITLE
thumbnail url keep pointing laravel-filemanager/images/shares

### ISSUE THREAD

**Issue by rebornishard** [UniSharp/laravel-filemanager#307] opened 2017-05-16 06:12 UTC
V 1.7.6
Laravel 5.4

I already set 'use_package_routes' => false,  
but thumbs still pointing to laravel-filemanager/images/shares

full url : 
"http://localhost/troll.id/laravel-filemanager/images/shares/2017-05-10_00-33-48.png?timestamp=1494913676"

image setting :
'base_directory' => 'public/uploads',

'images_folder_name' => 'images',
'files_folder_name'  => 'files',

'shared_folder_name' => 'shares',
'thumb_folder_name'  => 'shares/thumbs',

why it pointing to laravel-filemanager/images/shares not to public/uploads/images/shares

thanks

**Comment by rebornishard** [comment] 2017-05-16 09:10
temporary fix by alias in routing

**Comment by rodrigopeixotobr** [comment] 2017-05-16 18:55
@rebornishard Hi, how did you fixed please? Thanks.

**Comment by rebornishard** [comment] 2017-05-16 20:09
@rodrigopeixotobr after copy from master/src/routes.php
make a redirect route for every error, pointing it to right files / folders

**Comment by manozbiswas** [comment] 2017-05-26 09:30
Hi,

I have the same problem when I have changes the following
'use_package_routes' => true,

 'base_directory' => 'storage/app/public',

    'images_folder_name' => 'medias',
    'files_folder_name'  => 'medias',

    'shared_folder_name' => 'shares',
    'thumb_folder_name'  => 'thumbs',


Now all my folder files and images are uploaded in the storage/app/public directory but the thumbnail link points to laravel-filemanager/medias/1/5927ee2e7f3ae.jpg

But it should point to storage/app/public/medias/1/5927ee2e7f3ae.jpg

How did you fix your problem after changing the base directory
Any suggestion appretiated

**Comment by vertisan** [comment] 2017-05-30 00:23
Same problem, really annoying...

**Comment by Danthar** [comment] 2017-06-12 14:49
The problem is in https://github.com/UniSharp/laravel-filemanager/blob/master/src/traits/LfmHelpers.php#L113
This code assumes that if the default dir is not public then it should be available under the config.prefix path. 
This assumes that people have changed the default routes. But in this case we didn't and really there is no need.

I think that instead of using `config('lfm.prefix', 'laravel-filemanager')` it should be `config('lfm.urls_prefix', 'public')` instead. 

The urls_prefix description fits this scenario as well.

**Comment by Danthar** [comment] 2017-07-17 10:50
@g0110280 Nice that you closed it. But is a fix for this problem released? Because updating to the latest available (v1.8.1) proves that its still not working.

Making a redirect route for each error like @rebornishard is suggesting, is not an acceptable solution.

**Comment by g0110280** [comment] 2017-07-21 04:28
Here is the [config document](http://unisharp.github.io/laravel-filemanager/config#working-directory). `base_directory` only support value like `public` or `storage` or `resources` for now. Setting `base_directory` to `public/uploads` currently not supported. Pull requests are welcome.

**Comment by g0110280** [comment] 2018-10-19 08:33
This behavior is changed in `v2.0.0-alpha`. We now integrate with Laravel file system, path should be set in `config/filesystem.php` and the old config `base_directory` is deprecated now. If this still occurs in alpha versions please open new issues.

**Closed by g0110280** 2018-10-19 08:33 UTC
