### ISSUE TITLE
create a folder for a team when a teamleader user is created by admin 

### ISSUE THREAD

**Issue by jihadismail8** [UniSharp/laravel-filemanager#525] opened 2018-01-31 06:52 UTC
hello all , this is not a issue but i just wanted a small guide in how to  use this package to create a folder for a team when a teamleader user is created by admin , and only the team users can access their folder ?? it can be a little complicated , but any help i would be thankful for ! :)

**Comment by g0110280** [comment] 2018-12-02 07:34
Duplicate of #322 .

**Closed by g0110280** 2018-12-02 07:34 UTC
