### ISSUE TITLE
Can't install,  Class 'UniSharp\LaravelFilemanager\Lfm' not found

### ISSUE THREAD

**Issue by AnimalInstinct** [UniSharp/laravel-filemanager#627] opened 2018-07-04 11:30 UTC
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Ubuntu 18.04
 * Laravel version :  5.4.36
 * Package version : ~1.8
 * Steps to reproduce your issue : I am installing filemanager step by step, problem is after adding route group (Step 3)  I am getting this error on any artisan action

[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'UniSharp\LaravelFilemanager\Lfm' not found

 * Screenshots of browser console :
![screenshot from 2018-07-04 18-27-30](https://user-images.githubusercontent.com/7869979/42274731-f31660ec-7fb7-11e8-8800-8516a802cb16.png)

**Comment by jayenne** [comment] 2018-07-04 11:33
this loooks like a duplicate of this post... https://github.com/UniSharp/laravel-filemanager/issues/627

**Comment by AnimalInstinct** [comment] 2018-07-04 11:50
Post #627 duplicates post #627?

**Comment by jayenne** [comment] 2018-07-04 12:13
oops. https://github.com/UniSharp/laravel-filemanager/issues/625

**Comment by gwleuverink** [comment] 2018-07-05 08:23
@AnimalInstinct thanks for reporting this issue. It seems the behaviour you experience has been reported in #625, please refer to that issue.

**Closed** 2018-07-05 08:23 UTC
Labels: duplicate
