### ISSUE TITLE
The requested URL /laravel-filemanager/upload was not found on this server.

### ISSUE THREAD

**Issue by wassimhattab** [UniSharp/laravel-filemanager#309] opened 2017-05-16 08:58 UTC
Hello,
I installed laravel-filemanage package to add upload image feature in the ckeditor.
The tab for upload image is displayed now and when i choose image and click to upload the image i get this error after the uploading get 100%

```
The requested URL /laravel-filemanager/upload was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```
i didn't change anything in the config neither created folder to upload image to it

Any help?

**Comment by PendoNL** [comment] 2017-05-17 08:46
Sounds like you didn't register the Service Provider that sets up routing, or perhaps you have cached your routes? If you have the ServiceProvider in your app.php, try running `php artisan route:clear`, if that worked run `php artisan route:cache` afterwards to cache back your routes.

**Comment by wassimhattab** [comment] 2017-05-17 11:09
Yeah right i fixed the routing
Now i'm having this error 
```
BadMethodCallException in Controller.php line 283:
Method [upload] does not exist.
```

**Comment by PendoNL** [comment] 2017-05-17 11:21
You shouldn't need to add your own routes, besides that, the UploadController does the uploaden (see: https://github.com/UniSharp/laravel-filemanager/blob/master/src/routes.php). This file contains the routes for Laravel-filemanager.

As you can see here: https://github.com/UniSharp/laravel-filemanager/blob/master/src/LaravelFilemanagerServiceProvider.php#L20, the ServiceProvider registers the routes for you. You just have to make sure that your configuration file has `use_package_routes` set to true (see here: https://github.com/UniSharp/laravel-filemanager/blob/master/src/config/lfm.php#L11)

**Comment by wassimhattab** [comment] 2017-05-17 11:35
@PendoNL 
I did add the service provider from the first time in the app.js
```
Unisharp\Laravelfilemanager\LaravelFilemanagerServiceProvider::class,
Intervention\Image\ImageServiceProvider::class,
```

But it's not working and the use_package_routes its true in the config

**Comment by PendoNL** [comment] 2017-05-17 11:42
When you remove the routes you've added, does the output of `php artisan route:list` show the routes as programmed in the routes file of the package? (https://github.com/UniSharp/laravel-filemanager/blob/master/src/routes.php)

**Comment by wassimhattab** [comment] 2017-05-17 15:50
@PendoNL 

I removed the web and auth from middleware of the config because in my framework i'm not using auth of laravel and i'm using laravel 5.1 and added the user_field is 1...
Now when the upload reach 100% the folder is created and in my network tools i got the name of the image as following  
```
http://www.linteractif-ongoing.com/3alsouk/photos/1/Invalid upload request
```

Do you have any idea why the image is not uploading and getting invalid upload request?

**Comment by PendoNL** [comment] 2017-05-17 16:42
Haven't had that error, got passed a few errors in the last weeks but this is new for me. Just to Validate some things:

- What version of PHP are you using?
- Are you using GD or Imagick?
- Do you have exif enabled in PHP?
- Did you try a full re-install following the install instructions?

**Comment by wassimhattab** [comment] 2017-05-17 16:58
- PHP Version 5.6.30

Is the problem caused from php version?

**Comment by PendoNL** [comment] 2017-05-17 17:06
I doubt it, the package requires 5.4 as minimum PHP version. Perhaps the problem is fixed by this PR: https://github.com/UniSharp/laravel-filemanager/pull/300

I just noticed you refer to the lines that cause an error ($file->path() errors, this should be $file->getRealPath() on both lines). Info is in that PR my 2nd commands has the installation instructions. Can you try that?

**Comment by wassimhattab** [comment] 2017-05-17 17:17
@PendoNL 
I tried print_r($file->path) it returned error and tried to print_r($file->getRealPath()) return me 
```
/tmp/phpjv1kPF
```

And then removed the print and exit and kept go to the exception and return invalid error

**Comment by PendoNL** [comment] 2017-05-17 17:18
You have to follow the instructions in my 2nd comment in that PR. In your composer.json file add:

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/PendoNL/laravel-filemanager"
    }
],
```

And than change the version for file manager to this:
```
    "unisharp/laravel-filemanager": "dev-master",
```

Then composer update to pull my form and use that one until this is merged.

**Comment by ajiehatajie** [comment] 2017-06-03 09:15
Request URL:http://blog.dev/laravel-filemanager/upload
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:127.0.0.1:80
Referrer Policy:no-referrer-when-downgrade

Method [upload] does not exist

in composer.json

  `"unisharp/laravel-filemanager": "dev-master",
   `

**Comment by PendoNL** [comment] 2017-06-04 10:20
@ajiehatajie retry installation instructions, as you've clearly missed something along the way. My fix (as mentioned one post above yours) is merged in the repository already.

**Comment by ajiehatajie** [comment] 2017-06-12 06:53
thanks is re install and fix

**Closed** 2017-07-13 08:17 UTC
