### ISSUE TITLE
XMLHttpRequest cannot load laravel-filemanager

### ISSUE THREAD

**Issue by SilviaCh** [UniSharp/laravel-filemanager#591] opened 2018-05-08 20:15 UTC
This has never been a problem until this morning.

I'm currently using Laravel 5.2.45 as php framework, tinymce as wysiwyg editor and Unisharp/laravel-filemanger as image upload handler within tinymce.

This morning, when I try to upload an image through the filemanger (using the button at the end of source input bar), I noticed that the partial UI looks missing. When Inspect element, found this error message:
`[Error] XMLHttpRequest cannot load http://myweb/laravel-filemanager/jsonitems?working_dir=&type=Files&show_list=0&sort_type=alphabetic&_=1525726259621. Not allowed to request resource`

and a warming message:
`[blocked] The page at https://myweb.net/create was not allowed to display insecure content from http://myweb.net/laravel-filemanager/jsonitems?working_dir=&type=Files&show_list=0&sort_type=alphabetic&_=1525726259621.`

I think it might be some kind of mix content problem, so I have been trying to find where I can change the http to https and made sure that there is no reference to http://myweb.net throughout the entire repo...but the problem still exist. Also, I have cloudflare https rewrites on which should also rewrite any content from http to https...

Out of ideas...Any ideas?? thanks!!

**Comment by g0110280** [comment] 2018-12-05 16:06
Duplicate of #458 .

**Closed by g0110280** 2018-12-05 16:06 UTC
