### ISSUE TITLE
InvalidArgumentException in Finder.php line 546

### ISSUE THREAD

**Issue by serdarkok** [UniSharp/laravel-filemanager#131] opened 2016-10-12 14:53 UTC
Hi There;
I get that error message:
The "/media/disk/disk2/http/loopl/project/public/photos/1" directory does not exist.

1 is user id. you know.

If i create folder (user id = 1) than fix this. How can i auto create user id folder on photos directory?
How can i fix this?

my lfm.php :
*...
'use_package_routes' => true,
'middlewares' => ['web','auth'],
'prefix' => 'laravel-filemanager',
'allow_multi_user' => true,
'user_field' => 'id',
*...

**Comment by serdarkok** [comment] 2016-10-20 08:55
Please hellppp

**Comment by g0110280** [comment] 2016-10-25 02:51
@serdarkok Did it happen on your server?

**Comment by manoj-infrasssist** [comment] 2017-02-21 09:33
I am facing the same issue and still not solved. I anyone got the solution please let me know.

**Comment by g0110280** [comment] 2017-02-21 09:36
@manoj-infrasssist are you using `v1.7.0`? If so, please paste your error here.

**Comment by manoj-infrasssist** [comment] 2017-02-21 10:30
Yes, I'm using v1.7.0. 
I get the error "An error has occured: Internal Server Error"
And in console it is as below
InvalidArgumentException in Finder.php line 546:
The "C:\inetpub\wwwroot\odata/public/photos/12" directory does not exist.

**Comment by g0110280** [comment] 2017-02-22 02:49
Cannot reproduce this issue. I tested on Windows 10 and macOS 10.12, they worked just fine. User folder will be created automatically.

**Comment by manoj-infrasssist** [comment] 2017-02-22 07:06
May be below steps help in reproducing the issue.
I have deleted the user id folder from photos folder and then "browse server" from image properties window, then it shows empty listing . Here when I do rightclick->inspect element then in console it shows error 
InvalidArgumentException in Finder.php line 546:
The "C:\inetpub\wwwroot\odata/public/photos/12" directory does not exist.

**Comment by g0110280** [comment] 2017-04-19 17:57
@serdarkok @manoj-infrasssist please try `v1.7.2`.

**Comment by g0110280** [comment] 2017-04-28 06:45
Fixed in `v1.7.6`.

**Closed by g0110280** 2017-04-28 06:45 UTC
Labels: Cannot reproduce, done
