### ISSUE TITLE
lfm (standalone) closes window on selection but doesn't populate input or show thumbnail

### ISSUE THREAD

**Issue by jayenne** [UniSharp/laravel-filemanager#628] opened 2018-07-04 16:04 UTC
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : macOS
 * Laravel version : 5.6
 * Package version : ~1.8
 * Steps to reproduce your issue : fresh instal, followed instructions
 * Screenshots of browser console : nothing output to console.

**Comment by gwleuverink** [comment] 2018-07-05 08:46
Step taken to reproduce:

1. fresh L5.6.26 install
2. installed laravel-filemanager v1.8.5
3. copied the standalone input markup from documentation
4. added jQuery 3.3.1 & `/vendor/laravel-filemanager/js/lfm.js` to the welcome page
5. added `$('#lfm').filemanager('image');`

Everything works as expected. Image is populated in input and preview container.

Do you have any browser extensions installed that might block javascript execution?
Do you experience the same issue when you follow the steps above with fresh install?

**Comment by jayenne** [comment] 2018-07-05 10:18
Thanks Willem, I've done as you asked and it all works perfectly.
now to roll my sleves up and get dirty.

**Comment by jayenne** [comment] 2018-07-05 19:36
hmm, strangely it works perfectly with:
```
<script src="/vendor/laravel-filemanager/js/lfm.js" defer></script>

	<script type="text/javascript">
					
		$(document).ready(function(){
             if (jQuery) {  
               	var domain = '/filemanager';
               	$('#lfm').filemanager('image',{prefix:domain});
             }
          });
	</script>
```

but NOT with
```
<script type="text/javascript">
		
		function openFileManager($type="file"){
		
			var $prefix =  '/filemanager';
			lfm({type: $type, prefix:$prefix}, function(url, path) {});
		
		}
		
		var lfm = function(options, cb) {
			
			var route_prefix = (options && options.prefix) ? options.prefix : '/filemanager';
			window.open(route_prefix + '?type=' + options.type || 'file', 'FileManager', 'width=900,height=600');
			window.SetUrl = cb;
			
		}
				
	</script>
```
*I have change the path but diesn work with "laravel-filemanager" either
*for the second example I have added onclick="openFileManager('image')" to the <a> calling the function

**Comment by gwleuverink** [comment] 2018-07-06 14:52
I have just tried with your example. It's not clear where you are calling the openFileManager function from. I tried binding it to a click event and it worked.

Try binding your event handler explicitly like this:
`document.getElementById('open-manager-btn').addEventListener('click', openFileManager);`

or even on the button itself like so:
`<span onclick="openFileManager()">manager</span>`

I'll close this issue since it doesn't seem like an issue with the package. Feel free to ask in this thread tough if you need more help.

**Closed by gwleuverink** 2018-07-06 14:52 UTC
