### ISSUE TITLE
Share folder upload permission for admin

### ISSUE THREAD

**Issue by hamid80386** [UniSharp/laravel-filemanager#687] opened 2018-09-20 14:54 UTC
I wanna to have share folder and every user can use of it's files, but only for use!
And i need to some user like administrator or a user with (1) id can upload or delete files in share folder.
Is any way?

**Comment by g0110280** [comment] 2018-10-19 04:30
No such feature for now. We have added this to our backlogs.

**Comment by g0110280** [comment] 2018-12-03 06:36
Duplicate of another feature-request #322 .

**Closed by g0110280** 2018-12-03 06:36 UTC
Labels: feature-request
