### ISSUE TITLE
500 internal server error for upload images larger than 2MB

### ISSUE THREAD

**Issue by nekooee** [UniSharp/laravel-filemanager#592] opened 2018-05-09 06:33 UTC
when I try upload images larger than 2MB, I get the following error message:

server responded with 500 code

in header:
Request URL: http://mydomain.com/filemanager/upload
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade

my confog and php.in is:
lfm.php:
    'max_image_size' => 50000,
    'max_file_size' => 50000,
php.ini:
     upload_max_filesize=500M
     post_max_size=500M
     max_execution_time=900
     memory_limit=256M
     max_input_time=900
     

please help me :(

**Comment by FreedomKnight** [comment] 2018-05-09 06:41
what kind http server you use?
if you use nginx, maybe you need to set client_max_body_size.
if you use apache, you should set upload_max_filesize, post_max_size,

**Comment by nekooee** [comment] 2018-05-09 06:53
thank you. I use apache and set in php.ni "upload_max_filesize=500M , post_max_size=500M" but get error when upload images larger than 2MB.
I test in my host and in local. This problem exists in both!
I guess this problem is not in php.ini settings and is related to the file-manager.
I Need to help....

**Comment by nekooee** [comment] 2018-05-09 17:45
I change name and id from file to attachment. now upload form work. I tested a 10MB file , But the file could not be uploaded like AJAX, and displays the following error:

This page isn’t working
www.mydomain.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by nekooee** [comment] 2018-05-09 20:00
I found the problem. The problem is exactly with this part of the code:

```
 Image::make($file->getRealPath())
                    ->orientate() //Apply orientation from exif data
                    ->save($new_file_path);
```

Why does this part of the code give error 500 for big photos?

**Comment by nekooee** [comment] 2018-05-10 06:36
I add this code to uploadController.php:
```
error_reporting(E_ALL);
ini_set("display_errors", 1);
```
 and get this error :
> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 21844 bytes) in C:\test\project\testProject\vendor\intervention\image\src\Intervention\Image\Gd\Decoder.php on line 136

What should I do?

**Comment by nekooee** [comment] 2018-05-10 06:46
I change memory_limit from 256M to 500M and my problem sloved!
👍

**Comment by nekooee** [comment] 2018-05-11 15:50
A 500M memory is great for changing the size of a 11M photo. Most hosts have a memory limit of up to 250 MB. WordPress resizes photos without problems with 250 MB of memory.
Please optimize the resizing code.This is a huge constraint for our customers!

**Comment by g0110280** [comment] 2018-05-24 02:43
Thank you @nekooee , we will keep this in mind.

**Comment by hanabalonch** [comment] 2018-09-13 16:41
Hi, I got the same problem ` laravel-filemanager::lfm.error invalid` 
I have installed exif and fileinfo on my server.

I don't found another solution :/.

Thanks.

**Comment by g0110280** [comment] 2018-10-19 03:34
@hanabalonch please check exception messages in `storage/logs/laravel.log`. If you need further discussions, please open a new issue.

I have added summary of this issue to our [wiki](https://github.com/UniSharp/laravel-filemanager/wiki/500-error-when-uploading-large-files(over-2MB)), closing issue.

**Closed by g0110280** 2018-10-19 03:34 UTC

**Comment by djilali19** [comment] 2021-07-27 08:29
Hello,

thanks @nekooee I had the same problem, this last was solved by increasing the memory caused by Intervention / image

**Comment by Mahdi4a** [comment] 2022-05-08 10:02
i'v got the same problem i changed 
my config and php.in is:
lfm.php:
'max_image_size' => 50000,
'max_file_size' => 1000000,
php.ini:
upload_max_filesize=1024M
post_max_size=1024M
max_execution_time=900
memory_limit=1024M
max_input_time=900

and i also change timeout in 
Dropzone.options.uploadForm = {
      paramName: "upload[]", // The name that will be used to transfer the file
      uploadMultiple: false,
      parallelUploads: 5,
      timeout:1200000,


but it does'nt work i can't upload file higher than 100m
how can i fix this?

**Comment by jeamado** [comment] 2022-06-03 18:29
Disable ModSecurity in cPnel and try
