### ISSUE TITLE
Error while uploading file (pdf, txt etc..) "Action failed, due to server error."

### ISSUE THREAD

**Issue by waska14** [UniSharp/laravel-filemanager#216] opened 2017-03-02 08:08 UTC
**"Action failed, due to server error."**
This error is shown when I'm trying to upload any type of file (except images)
Link: **website../laravel-filemanager?type=Files&CKEditor=ce&CKEditorFuncNum=0&langCode=en**

lfm.php

> 'valid_file_mimetypes' => [
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/gif',
        'application/pdf',
        'text/plain',
    ],'

I'm trying to upload test.txt and test.pdf file but this error is shown.
any help?

**Comment by g0110280** [comment] 2017-03-02 08:35
Duplicate of #211 , validation message should be seen instead.

**Comment by waska14** [comment] 2017-03-02 10:10
I have seen the issue (#211) but there is no solution.

The validation message comes only when I'm trying to upload files, not images.

**Comment by g0110280** [comment] 2017-03-24 08:42
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.

**Closed** 2017-03-29 08:57 UTC
Labels: done, duplicate
