### ISSUE TITLE
SOS!

### ISSUE THREAD

**Issue by rhellow** [UniSharp/laravel-filemanager#985] opened 2020-09-11 16:43 UTC
Hello! I'm a student, new to Laravel & I would like to seek assistance from you as soon as possible!
I'm currently using Laravel v7/8. I need to build a file management system with Windows IIS Server and not any other cloud. Could you provide me some guidances/documentations on that. I can't even run composer require unisharp/laravel-filemanager.

**Comment by streamtw** [comment] 2020-09-13 07:06
Duplicate of #986 .

**Closed by streamtw** 2020-09-13 07:06 UTC
