### ISSUE TITLE
please add search option in V2.0.0 version.

### ISSUE THREAD

**Issue by nekooee** [UniSharp/laravel-filemanager#535] opened 2018-02-09 11:31 UTC
please add search option in V2.0.0 version.

**Comment by youchenlee** [comment] 2018-02-09 13:32
Search by filename?

We do have a plan to develop a filemanager extension that stores file metadata in MySQL. That makes it searchable.

**Comment by nekooee** [comment] 2018-02-09 13:45
yes search by filename. 

> We do have a plan to develop a filemanager extension that stores file metadata in MySQL. That makes it searchable.

very good. I'm impatiently waiting. 
thank you. :)

**Comment by g0110280** [comment] 2018-12-05 15:24
Duplicate of #316 .

**Closed by g0110280** 2018-12-05 15:24 UTC
Labels: duplicate

**Comment by masumbillahbd** [comment] 2021-08-21 12:18
how to implement search box in laravel file manager v2.0.0?
