### ISSUE TITLE
how remove /laravel-filemanager/ from urls?

### ISSUE THREAD

**Issue by farshidrezaei** [UniSharp/laravel-filemanager#386] opened 2017-08-06 11:22 UTC
when upload an image, "/laravel-filemanager" added to first of urls.
and in site that url not show if user not logined.

**Comment by Enethion** [comment] 2017-08-10 08:56
I agree. Also, when I set `'base_directory'` to `'public/storage'` accessing files via `my.domain/laravel-filemanager/file_path` has no sense. [By default `'base_directory'` is set to `'public'`, so even then special route has no valid reason]

**Comment by farshidrezaei** [comment] 2017-08-11 09:00
i delete 20 first charecters by sub_str.  But this is not the right way. plaese say how fix it.

**Comment by g0110280** [comment] 2017-08-21 06:19
@farshidrezaei 
> in site that url not show if user not logined.

This was fixed in the latest version.

And if you set `base_directory` to `public`, `laravel-filemanager` won't be included in urls.

**Comment by farshidrezaei** [comment] 2017-08-21 07:50
@g0110280

but i have to change base_directory, because i use shared hosting. 

and I have some articles that do not require authentication. 

what i do?

**Comment by VizuaaLOG** [comment] 2017-08-22 12:01
I think there should be an additional option that adds the prefix to the path if desired. I'm just having to modify the returned urls in javascript to strip the prefix out.

**Comment by farshidrezaei** [comment] 2017-08-22 12:07
@VizuasLOG 

Why should  /laravel-filemanager/ exist?

**Comment by cakesforfree** [comment] 2017-08-30 14:43
I am having the same problem, i am using a shared hosting and i need to change my base_directory to: public/../../public_html. 

With this I get my files uploaded to the server but the images don't appear.
![image](https://user-images.githubusercontent.com/13759233/29878166-05e4c818-8d5f-11e7-94b8-a2c6f4231a17.png)

and when i click them I it shows the "/laravel-filemanager/ " and it is so annoying I don't even understand why is this happening:
![image](https://user-images.githubusercontent.com/13759233/29878266-4d2d8764-8d5f-11e7-903d-4c91cd588292.png)

**Comment by cakesforfree** [comment] 2017-08-31 01:07
Damn, i finally understood the purpose of "url_prefix", in my case i used it this way:

This is what i need it to do:
![image](https://user-images.githubusercontent.com/13759233/29901640-5f85edb4-8db6-11e7-819f-692473667673.png)


and this is how you use the url_prefix:
![image](https://user-images.githubusercontent.com/13759233/29901653-6cd2417a-8db6-11e7-9b15-5f4e3e2c8fc5.png)

with this you can jump into different folders, and get access to the public_html in a shared host.

**Comment by cakesforfree** [comment] 2017-08-31 08:42
how do you work around this? is there a way to avoid adding the "/laravel-filemanager/" path? I though i had it, but I still can't make it work 😢

**Comment by cakesforfree** [comment] 2017-08-31 14:38
I ended up removing this piece of code to remove the " /laravel-filemanager/" path : 


![image](https://user-images.githubusercontent.com/13759233/29929071-c6a64fe0-8e27-11e7-93e5-11031e68b25e.png)
[\vendor\unisharp\laravel-filemanager\src\traits\LfmHelpers.php]

**Comment by farshidrezaei** [comment] 2017-08-31 14:50
@cakesforfree 
and it's work?

**Comment by cakesforfree** [comment] 2017-08-31 14:53
yes. 
this is my config/lfm.php
![image](https://user-images.githubusercontent.com/13759233/29929819-d0596e9e-8e29-11e7-8084-d4a2e2618042.png)

**Comment by gwleuverink** [comment] 2017-08-31 14:56
@cakesforfree If I read your first screenshot correctly editing the 'prefix' config so it's an empty string accomplishes exactly the same thing. I don't see that option in the config though. Could it be that that first parameter in the config helper function should actually be 'url_prefix'? @g0110280

**Comment by cakesforfree** [comment] 2017-08-31 15:01
@gwleuverink if i leave the "prefix" parameter emty:
![image](https://user-images.githubusercontent.com/13759233/29930142-cd6bd5a4-8e2a-11e7-9955-5b95d4071792.png)

i get this error: 
![image](https://user-images.githubusercontent.com/13759233/29930173-e64a339a-8e2a-11e7-997c-66687dfe6b07.png)

**Comment by gwleuverink** [comment] 2017-08-31 15:18
It's not empty in your config screenshot. it has to be something, otherwise the package will use the base url as it's route, and that main route is usually reserved by your home page.

But what is it exactly what you are trying to do? I want to help but I'm a little confused.

My understanding is that the prefix in the route to the filemanager itself is fine, but when you use it with WYSIWYG integration you also have the prefix prepended to the string that is pasted into your editor. Is that right?

On a different note: It looks like the base directory you are using might be giving some problems also. Can you share a screenshot of your project structure? (root of the app and all folders expanded to the directory you want to save the files in)

**Comment by gwleuverink** [comment] 2017-08-31 15:25
@cakesforfree did you find the problem?

**Comment by cakesforfree** [comment] 2017-08-31 16:17
@gwleuverink sorry, i am not sure if I understand your question, but if I leave the "prefix" option  empty, in my config file, it gives me a NotFoundHttpException error.

![image](https://user-images.githubusercontent.com/13759233/29933659-a6285ee4-8e35-11e7-8a64-6ba1011bd2c8.png)

**Comment by gwleuverink** [comment] 2017-09-01 07:06
Okay. sorry it seems I was a bit confused as to what the problem you are experiencing is exactly. Do I understand correctly that the 'laravel-filemanager' prefix in the route you are using is not the problem, but rather that all images that are loaded have that prefix in the url also?

That might have something to do with the 'base_directory' value in your config. 
Can you post a folded out project structure here? So we can see how the directories of your shared hosting is organised.

**Comment by abad93** [comment] 2017-09-05 08:31
You have to change the lfm.js (public/vendor/laravel-filemanager/js/lfm.js).
In that file you can see the url /laravel-filemanager. 

![screen shot 2017-09-05 at 4 27 09 pm](https://user-images.githubusercontent.com/20398332/30052277-8a340de8-9257-11e7-815e-eb2432956739.png)

**Comment by srggroup** [comment] 2017-11-29 14:59
The problem is in the getPathPrefix function, around line 112 in LfmHelpers.php
`if ($type === 'url' && $base_directory !== 'public')...`

I've configured the LFM to use the public/upload base directory. And because of this the function will return the `laravel-filemanager` prefixed path, if the `base_directory` config is not `public`. I don't know the reason of this, but for me the temporary solution was to change back the `base_directory` config to `public`, and the `images_folder_name` to `upload/img'. This is a hack, but working.

But please fix this somehow please.

**Closed** 2018-02-01 09:21 UTC

**Comment by zinnia-visible** [comment] 2020-07-27 04:33
Let me know, now image file save this format http://localhost:8004/storage/files/shares/Group66.png and want to change /storage/files/shares/Group66.png and how to remove app url in db
